server:
  port: 8080
logging:
  level:
    root: INFO
spring:
  application:
    name: spring-kafka-protobuf
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      topic-name: product.issued
      properties:
        schema.registry.url: "http://localhost:8081"
        partition.assignment.strategy: org.apache.kafka.clients.consumer.RoundRobinAssignor
        specific.protobuf.value.type: ru.prytkovv.demo.proto.Product
        max.poll.interval.ms: 30000
      group-id: "spring-kafka-protobuf"
      value-deserializer: io.confluent.kafka.serializers.protobuf.KafkaProtobufDeserializer
