# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: product.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rproduct.proto\x12\x11\x63om.example.kafka\x1a\x1fgoogle/protobuf/timestamp.proto\"Z\n\x05Image\x12\x0f\n\x07\x63ontent\x18\x01 \x01(\x0c\x12\r\n\x05width\x18\x02 \x01(\x05\x12\x0e\n\x06height\x18\x03 \x01(\x05\x12\x0e\n\x06\x66ormat\x18\x04 \x01(\t\x12\x11\n\tcamera_id\x18\x05 \x01(\t\"\xd6\x01\n\x07Product\x12\'\n\x05image\x18\x01 \x01(\x0b\x32\x18.com.example.kafka.Image\x12\x0f\n\x07\x62\x61rcode\x18\x02 \x01(\t\x12\x13\n\x0b\x63\x61tegory_id\x18\x03 \x01(\x05\x12\x17\n\x0fmanufacturer_id\x18\x04 \x01(\x05\x12\x33\n\x0fmanufactured_at\x18\x05 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12.\n\ncreated_at\x18\x06 \x01(\x0b\x32\x1a.google.protobuf.TimestampB(\n\x16ru.prytkovv.demo.protoB\x0cProductProtoP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'product_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\026ru.prytkovv.demo.protoB\014ProductProtoP\001'
  _globals['_IMAGE']._serialized_start=69
  _globals['_IMAGE']._serialized_end=159
  _globals['_PRODUCT']._serialized_start=162
  _globals['_PRODUCT']._serialized_end=376
# @@protoc_insertion_point(module_scope)
