// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: product.proto

package ru.prytkovv.demo.proto;

public interface ImageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.example.kafka.Image)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bytes content = 1;</code>
   * @return The content.
   */
  com.google.protobuf.ByteString getContent();

  /**
   * <code>int32 width = 2;</code>
   * @return The width.
   */
  int getWidth();

  /**
   * <code>int32 height = 3;</code>
   * @return The height.
   */
  int getHeight();

  /**
   * <code>string format = 4;</code>
   * @return The format.
   */
  java.lang.String getFormat();
  /**
   * <code>string format = 4;</code>
   * @return The bytes for format.
   */
  com.google.protobuf.ByteString
      getFormatBytes();

  /**
   * <code>string camera_id = 5;</code>
   * @return The cameraId.
   */
  java.lang.String getCameraId();
  /**
   * <code>string camera_id = 5;</code>
   * @return The bytes for cameraId.
   */
  com.google.protobuf.ByteString
      getCameraIdBytes();
}
