// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: product.proto

package ru.prytkovv.demo.proto;

public final class ProductProto {
  private ProductProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_example_kafka_Image_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_example_kafka_Image_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_example_kafka_Product_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_example_kafka_Product_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rproduct.proto\022\021com.example.kafka\032\037goog" +
      "le/protobuf/timestamp.proto\"Z\n\005Image\022\017\n\007" +
      "content\030\001 \001(\014\022\r\n\005width\030\002 \001(\005\022\016\n\006height\030\003" +
      " \001(\005\022\016\n\006format\030\004 \001(\t\022\021\n\tcamera_id\030\005 \001(\t\"" +
      "\326\001\n\007Product\022\'\n\005image\030\001 \001(\0132\030.com.example" +
      ".kafka.Image\022\017\n\007barcode\030\002 \001(\t\022\023\n\013categor" +
      "y_id\030\003 \001(\005\022\027\n\017manufacturer_id\030\004 \001(\005\0223\n\017m" +
      "anufactured_at\030\005 \001(\0132\032.google.protobuf.T" +
      "imestamp\022.\n\ncreated_at\030\006 \001(\0132\032.google.pr" +
      "otobuf.TimestampB(\n\026ru.prytkovv.demo.pro" +
      "toB\014ProductProtoP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.TimestampProto.getDescriptor(),
        });
    internal_static_com_example_kafka_Image_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_example_kafka_Image_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_example_kafka_Image_descriptor,
        new java.lang.String[] { "Content", "Width", "Height", "Format", "CameraId", });
    internal_static_com_example_kafka_Product_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_example_kafka_Product_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_example_kafka_Product_descriptor,
        new java.lang.String[] { "Image", "Barcode", "CategoryId", "ManufacturerId", "ManufacturedAt", "CreatedAt", });
    com.google.protobuf.TimestampProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
