// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: product.proto

package ru.prytkovv.demo.proto;

/**
 * Protobuf type {@code com.example.kafka.Product}
 */
public final class Product extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.example.kafka.Product)
    ProductOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Product.newBuilder() to construct.
  private Product(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Product() {
    barcode_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new Product();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return ru.prytkovv.demo.proto.ProductProto.internal_static_com_example_kafka_Product_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return ru.prytkovv.demo.proto.ProductProto.internal_static_com_example_kafka_Product_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            ru.prytkovv.demo.proto.Product.class, ru.prytkovv.demo.proto.Product.Builder.class);
  }

  private int bitField0_;
  public static final int IMAGE_FIELD_NUMBER = 1;
  private ru.prytkovv.demo.proto.Image image_;
  /**
   * <code>.com.example.kafka.Image image = 1;</code>
   * @return Whether the image field is set.
   */
  @java.lang.Override
  public boolean hasImage() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>.com.example.kafka.Image image = 1;</code>
   * @return The image.
   */
  @java.lang.Override
  public ru.prytkovv.demo.proto.Image getImage() {
    return image_ == null ? ru.prytkovv.demo.proto.Image.getDefaultInstance() : image_;
  }
  /**
   * <code>.com.example.kafka.Image image = 1;</code>
   */
  @java.lang.Override
  public ru.prytkovv.demo.proto.ImageOrBuilder getImageOrBuilder() {
    return image_ == null ? ru.prytkovv.demo.proto.Image.getDefaultInstance() : image_;
  }

  public static final int BARCODE_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile java.lang.Object barcode_ = "";
  /**
   * <code>string barcode = 2;</code>
   * @return The barcode.
   */
  @java.lang.Override
  public java.lang.String getBarcode() {
    java.lang.Object ref = barcode_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      barcode_ = s;
      return s;
    }
  }
  /**
   * <code>string barcode = 2;</code>
   * @return The bytes for barcode.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getBarcodeBytes() {
    java.lang.Object ref = barcode_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      barcode_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CATEGORY_ID_FIELD_NUMBER = 3;
  private int categoryId_ = 0;
  /**
   * <code>int32 category_id = 3;</code>
   * @return The categoryId.
   */
  @java.lang.Override
  public int getCategoryId() {
    return categoryId_;
  }

  public static final int MANUFACTURER_ID_FIELD_NUMBER = 4;
  private int manufacturerId_ = 0;
  /**
   * <code>int32 manufacturer_id = 4;</code>
   * @return The manufacturerId.
   */
  @java.lang.Override
  public int getManufacturerId() {
    return manufacturerId_;
  }

  public static final int MANUFACTURED_AT_FIELD_NUMBER = 5;
  private com.google.protobuf.Timestamp manufacturedAt_;
  /**
   * <code>.google.protobuf.Timestamp manufactured_at = 5;</code>
   * @return Whether the manufacturedAt field is set.
   */
  @java.lang.Override
  public boolean hasManufacturedAt() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <code>.google.protobuf.Timestamp manufactured_at = 5;</code>
   * @return The manufacturedAt.
   */
  @java.lang.Override
  public com.google.protobuf.Timestamp getManufacturedAt() {
    return manufacturedAt_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : manufacturedAt_;
  }
  /**
   * <code>.google.protobuf.Timestamp manufactured_at = 5;</code>
   */
  @java.lang.Override
  public com.google.protobuf.TimestampOrBuilder getManufacturedAtOrBuilder() {
    return manufacturedAt_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : manufacturedAt_;
  }

  public static final int CREATED_AT_FIELD_NUMBER = 6;
  private com.google.protobuf.Timestamp createdAt_;
  /**
   * <code>.google.protobuf.Timestamp created_at = 6;</code>
   * @return Whether the createdAt field is set.
   */
  @java.lang.Override
  public boolean hasCreatedAt() {
    return ((bitField0_ & 0x00000004) != 0);
  }
  /**
   * <code>.google.protobuf.Timestamp created_at = 6;</code>
   * @return The createdAt.
   */
  @java.lang.Override
  public com.google.protobuf.Timestamp getCreatedAt() {
    return createdAt_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : createdAt_;
  }
  /**
   * <code>.google.protobuf.Timestamp created_at = 6;</code>
   */
  @java.lang.Override
  public com.google.protobuf.TimestampOrBuilder getCreatedAtOrBuilder() {
    return createdAt_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : createdAt_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeMessage(1, getImage());
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(barcode_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, barcode_);
    }
    if (categoryId_ != 0) {
      output.writeInt32(3, categoryId_);
    }
    if (manufacturerId_ != 0) {
      output.writeInt32(4, manufacturerId_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      output.writeMessage(5, getManufacturedAt());
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      output.writeMessage(6, getCreatedAt());
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getImage());
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(barcode_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, barcode_);
    }
    if (categoryId_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(3, categoryId_);
    }
    if (manufacturerId_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(4, manufacturerId_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(5, getManufacturedAt());
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(6, getCreatedAt());
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof ru.prytkovv.demo.proto.Product)) {
      return super.equals(obj);
    }
    ru.prytkovv.demo.proto.Product other = (ru.prytkovv.demo.proto.Product) obj;

    if (hasImage() != other.hasImage()) return false;
    if (hasImage()) {
      if (!getImage()
          .equals(other.getImage())) return false;
    }
    if (!getBarcode()
        .equals(other.getBarcode())) return false;
    if (getCategoryId()
        != other.getCategoryId()) return false;
    if (getManufacturerId()
        != other.getManufacturerId()) return false;
    if (hasManufacturedAt() != other.hasManufacturedAt()) return false;
    if (hasManufacturedAt()) {
      if (!getManufacturedAt()
          .equals(other.getManufacturedAt())) return false;
    }
    if (hasCreatedAt() != other.hasCreatedAt()) return false;
    if (hasCreatedAt()) {
      if (!getCreatedAt()
          .equals(other.getCreatedAt())) return false;
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasImage()) {
      hash = (37 * hash) + IMAGE_FIELD_NUMBER;
      hash = (53 * hash) + getImage().hashCode();
    }
    hash = (37 * hash) + BARCODE_FIELD_NUMBER;
    hash = (53 * hash) + getBarcode().hashCode();
    hash = (37 * hash) + CATEGORY_ID_FIELD_NUMBER;
    hash = (53 * hash) + getCategoryId();
    hash = (37 * hash) + MANUFACTURER_ID_FIELD_NUMBER;
    hash = (53 * hash) + getManufacturerId();
    if (hasManufacturedAt()) {
      hash = (37 * hash) + MANUFACTURED_AT_FIELD_NUMBER;
      hash = (53 * hash) + getManufacturedAt().hashCode();
    }
    if (hasCreatedAt()) {
      hash = (37 * hash) + CREATED_AT_FIELD_NUMBER;
      hash = (53 * hash) + getCreatedAt().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static ru.prytkovv.demo.proto.Product parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ru.prytkovv.demo.proto.Product parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ru.prytkovv.demo.proto.Product parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ru.prytkovv.demo.proto.Product parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ru.prytkovv.demo.proto.Product parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ru.prytkovv.demo.proto.Product parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ru.prytkovv.demo.proto.Product parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ru.prytkovv.demo.proto.Product parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static ru.prytkovv.demo.proto.Product parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static ru.prytkovv.demo.proto.Product parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static ru.prytkovv.demo.proto.Product parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ru.prytkovv.demo.proto.Product parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(ru.prytkovv.demo.proto.Product prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.example.kafka.Product}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.example.kafka.Product)
      ru.prytkovv.demo.proto.ProductOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ru.prytkovv.demo.proto.ProductProto.internal_static_com_example_kafka_Product_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ru.prytkovv.demo.proto.ProductProto.internal_static_com_example_kafka_Product_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ru.prytkovv.demo.proto.Product.class, ru.prytkovv.demo.proto.Product.Builder.class);
    }

    // Construct using ru.prytkovv.demo.proto.Product.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getImageFieldBuilder();
        getManufacturedAtFieldBuilder();
        getCreatedAtFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      image_ = null;
      if (imageBuilder_ != null) {
        imageBuilder_.dispose();
        imageBuilder_ = null;
      }
      barcode_ = "";
      categoryId_ = 0;
      manufacturerId_ = 0;
      manufacturedAt_ = null;
      if (manufacturedAtBuilder_ != null) {
        manufacturedAtBuilder_.dispose();
        manufacturedAtBuilder_ = null;
      }
      createdAt_ = null;
      if (createdAtBuilder_ != null) {
        createdAtBuilder_.dispose();
        createdAtBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return ru.prytkovv.demo.proto.ProductProto.internal_static_com_example_kafka_Product_descriptor;
    }

    @java.lang.Override
    public ru.prytkovv.demo.proto.Product getDefaultInstanceForType() {
      return ru.prytkovv.demo.proto.Product.getDefaultInstance();
    }

    @java.lang.Override
    public ru.prytkovv.demo.proto.Product build() {
      ru.prytkovv.demo.proto.Product result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public ru.prytkovv.demo.proto.Product buildPartial() {
      ru.prytkovv.demo.proto.Product result = new ru.prytkovv.demo.proto.Product(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(ru.prytkovv.demo.proto.Product result) {
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.image_ = imageBuilder_ == null
            ? image_
            : imageBuilder_.build();
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.barcode_ = barcode_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.categoryId_ = categoryId_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.manufacturerId_ = manufacturerId_;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.manufacturedAt_ = manufacturedAtBuilder_ == null
            ? manufacturedAt_
            : manufacturedAtBuilder_.build();
        to_bitField0_ |= 0x00000002;
      }
      if (((from_bitField0_ & 0x00000020) != 0)) {
        result.createdAt_ = createdAtBuilder_ == null
            ? createdAt_
            : createdAtBuilder_.build();
        to_bitField0_ |= 0x00000004;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof ru.prytkovv.demo.proto.Product) {
        return mergeFrom((ru.prytkovv.demo.proto.Product)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(ru.prytkovv.demo.proto.Product other) {
      if (other == ru.prytkovv.demo.proto.Product.getDefaultInstance()) return this;
      if (other.hasImage()) {
        mergeImage(other.getImage());
      }
      if (!other.getBarcode().isEmpty()) {
        barcode_ = other.barcode_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      if (other.getCategoryId() != 0) {
        setCategoryId(other.getCategoryId());
      }
      if (other.getManufacturerId() != 0) {
        setManufacturerId(other.getManufacturerId());
      }
      if (other.hasManufacturedAt()) {
        mergeManufacturedAt(other.getManufacturedAt());
      }
      if (other.hasCreatedAt()) {
        mergeCreatedAt(other.getCreatedAt());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              input.readMessage(
                  getImageFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              barcode_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 24: {
              categoryId_ = input.readInt32();
              bitField0_ |= 0x00000004;
              break;
            } // case 24
            case 32: {
              manufacturerId_ = input.readInt32();
              bitField0_ |= 0x00000008;
              break;
            } // case 32
            case 42: {
              input.readMessage(
                  getManufacturedAtFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000010;
              break;
            } // case 42
            case 50: {
              input.readMessage(
                  getCreatedAtFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000020;
              break;
            } // case 50
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private ru.prytkovv.demo.proto.Image image_;
    private com.google.protobuf.SingleFieldBuilderV3<
        ru.prytkovv.demo.proto.Image, ru.prytkovv.demo.proto.Image.Builder, ru.prytkovv.demo.proto.ImageOrBuilder> imageBuilder_;
    /**
     * <code>.com.example.kafka.Image image = 1;</code>
     * @return Whether the image field is set.
     */
    public boolean hasImage() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>.com.example.kafka.Image image = 1;</code>
     * @return The image.
     */
    public ru.prytkovv.demo.proto.Image getImage() {
      if (imageBuilder_ == null) {
        return image_ == null ? ru.prytkovv.demo.proto.Image.getDefaultInstance() : image_;
      } else {
        return imageBuilder_.getMessage();
      }
    }
    /**
     * <code>.com.example.kafka.Image image = 1;</code>
     */
    public Builder setImage(ru.prytkovv.demo.proto.Image value) {
      if (imageBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        image_ = value;
      } else {
        imageBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.com.example.kafka.Image image = 1;</code>
     */
    public Builder setImage(
        ru.prytkovv.demo.proto.Image.Builder builderForValue) {
      if (imageBuilder_ == null) {
        image_ = builderForValue.build();
      } else {
        imageBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.com.example.kafka.Image image = 1;</code>
     */
    public Builder mergeImage(ru.prytkovv.demo.proto.Image value) {
      if (imageBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0) &&
          image_ != null &&
          image_ != ru.prytkovv.demo.proto.Image.getDefaultInstance()) {
          getImageBuilder().mergeFrom(value);
        } else {
          image_ = value;
        }
      } else {
        imageBuilder_.mergeFrom(value);
      }
      if (image_ != null) {
        bitField0_ |= 0x00000001;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.com.example.kafka.Image image = 1;</code>
     */
    public Builder clearImage() {
      bitField0_ = (bitField0_ & ~0x00000001);
      image_ = null;
      if (imageBuilder_ != null) {
        imageBuilder_.dispose();
        imageBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.com.example.kafka.Image image = 1;</code>
     */
    public ru.prytkovv.demo.proto.Image.Builder getImageBuilder() {
      bitField0_ |= 0x00000001;
      onChanged();
      return getImageFieldBuilder().getBuilder();
    }
    /**
     * <code>.com.example.kafka.Image image = 1;</code>
     */
    public ru.prytkovv.demo.proto.ImageOrBuilder getImageOrBuilder() {
      if (imageBuilder_ != null) {
        return imageBuilder_.getMessageOrBuilder();
      } else {
        return image_ == null ?
            ru.prytkovv.demo.proto.Image.getDefaultInstance() : image_;
      }
    }
    /**
     * <code>.com.example.kafka.Image image = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        ru.prytkovv.demo.proto.Image, ru.prytkovv.demo.proto.Image.Builder, ru.prytkovv.demo.proto.ImageOrBuilder> 
        getImageFieldBuilder() {
      if (imageBuilder_ == null) {
        imageBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            ru.prytkovv.demo.proto.Image, ru.prytkovv.demo.proto.Image.Builder, ru.prytkovv.demo.proto.ImageOrBuilder>(
                getImage(),
                getParentForChildren(),
                isClean());
        image_ = null;
      }
      return imageBuilder_;
    }

    private java.lang.Object barcode_ = "";
    /**
     * <code>string barcode = 2;</code>
     * @return The barcode.
     */
    public java.lang.String getBarcode() {
      java.lang.Object ref = barcode_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        barcode_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string barcode = 2;</code>
     * @return The bytes for barcode.
     */
    public com.google.protobuf.ByteString
        getBarcodeBytes() {
      java.lang.Object ref = barcode_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        barcode_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string barcode = 2;</code>
     * @param value The barcode to set.
     * @return This builder for chaining.
     */
    public Builder setBarcode(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      barcode_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>string barcode = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearBarcode() {
      barcode_ = getDefaultInstance().getBarcode();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <code>string barcode = 2;</code>
     * @param value The bytes for barcode to set.
     * @return This builder for chaining.
     */
    public Builder setBarcodeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      barcode_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private int categoryId_ ;
    /**
     * <code>int32 category_id = 3;</code>
     * @return The categoryId.
     */
    @java.lang.Override
    public int getCategoryId() {
      return categoryId_;
    }
    /**
     * <code>int32 category_id = 3;</code>
     * @param value The categoryId to set.
     * @return This builder for chaining.
     */
    public Builder setCategoryId(int value) {

      categoryId_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>int32 category_id = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearCategoryId() {
      bitField0_ = (bitField0_ & ~0x00000004);
      categoryId_ = 0;
      onChanged();
      return this;
    }

    private int manufacturerId_ ;
    /**
     * <code>int32 manufacturer_id = 4;</code>
     * @return The manufacturerId.
     */
    @java.lang.Override
    public int getManufacturerId() {
      return manufacturerId_;
    }
    /**
     * <code>int32 manufacturer_id = 4;</code>
     * @param value The manufacturerId to set.
     * @return This builder for chaining.
     */
    public Builder setManufacturerId(int value) {

      manufacturerId_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>int32 manufacturer_id = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearManufacturerId() {
      bitField0_ = (bitField0_ & ~0x00000008);
      manufacturerId_ = 0;
      onChanged();
      return this;
    }

    private com.google.protobuf.Timestamp manufacturedAt_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> manufacturedAtBuilder_;
    /**
     * <code>.google.protobuf.Timestamp manufactured_at = 5;</code>
     * @return Whether the manufacturedAt field is set.
     */
    public boolean hasManufacturedAt() {
      return ((bitField0_ & 0x00000010) != 0);
    }
    /**
     * <code>.google.protobuf.Timestamp manufactured_at = 5;</code>
     * @return The manufacturedAt.
     */
    public com.google.protobuf.Timestamp getManufacturedAt() {
      if (manufacturedAtBuilder_ == null) {
        return manufacturedAt_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : manufacturedAt_;
      } else {
        return manufacturedAtBuilder_.getMessage();
      }
    }
    /**
     * <code>.google.protobuf.Timestamp manufactured_at = 5;</code>
     */
    public Builder setManufacturedAt(com.google.protobuf.Timestamp value) {
      if (manufacturedAtBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        manufacturedAt_ = value;
      } else {
        manufacturedAtBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp manufactured_at = 5;</code>
     */
    public Builder setManufacturedAt(
        com.google.protobuf.Timestamp.Builder builderForValue) {
      if (manufacturedAtBuilder_ == null) {
        manufacturedAt_ = builderForValue.build();
      } else {
        manufacturedAtBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp manufactured_at = 5;</code>
     */
    public Builder mergeManufacturedAt(com.google.protobuf.Timestamp value) {
      if (manufacturedAtBuilder_ == null) {
        if (((bitField0_ & 0x00000010) != 0) &&
          manufacturedAt_ != null &&
          manufacturedAt_ != com.google.protobuf.Timestamp.getDefaultInstance()) {
          getManufacturedAtBuilder().mergeFrom(value);
        } else {
          manufacturedAt_ = value;
        }
      } else {
        manufacturedAtBuilder_.mergeFrom(value);
      }
      if (manufacturedAt_ != null) {
        bitField0_ |= 0x00000010;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp manufactured_at = 5;</code>
     */
    public Builder clearManufacturedAt() {
      bitField0_ = (bitField0_ & ~0x00000010);
      manufacturedAt_ = null;
      if (manufacturedAtBuilder_ != null) {
        manufacturedAtBuilder_.dispose();
        manufacturedAtBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp manufactured_at = 5;</code>
     */
    public com.google.protobuf.Timestamp.Builder getManufacturedAtBuilder() {
      bitField0_ |= 0x00000010;
      onChanged();
      return getManufacturedAtFieldBuilder().getBuilder();
    }
    /**
     * <code>.google.protobuf.Timestamp manufactured_at = 5;</code>
     */
    public com.google.protobuf.TimestampOrBuilder getManufacturedAtOrBuilder() {
      if (manufacturedAtBuilder_ != null) {
        return manufacturedAtBuilder_.getMessageOrBuilder();
      } else {
        return manufacturedAt_ == null ?
            com.google.protobuf.Timestamp.getDefaultInstance() : manufacturedAt_;
      }
    }
    /**
     * <code>.google.protobuf.Timestamp manufactured_at = 5;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> 
        getManufacturedAtFieldBuilder() {
      if (manufacturedAtBuilder_ == null) {
        manufacturedAtBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>(
                getManufacturedAt(),
                getParentForChildren(),
                isClean());
        manufacturedAt_ = null;
      }
      return manufacturedAtBuilder_;
    }

    private com.google.protobuf.Timestamp createdAt_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> createdAtBuilder_;
    /**
     * <code>.google.protobuf.Timestamp created_at = 6;</code>
     * @return Whether the createdAt field is set.
     */
    public boolean hasCreatedAt() {
      return ((bitField0_ & 0x00000020) != 0);
    }
    /**
     * <code>.google.protobuf.Timestamp created_at = 6;</code>
     * @return The createdAt.
     */
    public com.google.protobuf.Timestamp getCreatedAt() {
      if (createdAtBuilder_ == null) {
        return createdAt_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : createdAt_;
      } else {
        return createdAtBuilder_.getMessage();
      }
    }
    /**
     * <code>.google.protobuf.Timestamp created_at = 6;</code>
     */
    public Builder setCreatedAt(com.google.protobuf.Timestamp value) {
      if (createdAtBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        createdAt_ = value;
      } else {
        createdAtBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp created_at = 6;</code>
     */
    public Builder setCreatedAt(
        com.google.protobuf.Timestamp.Builder builderForValue) {
      if (createdAtBuilder_ == null) {
        createdAt_ = builderForValue.build();
      } else {
        createdAtBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp created_at = 6;</code>
     */
    public Builder mergeCreatedAt(com.google.protobuf.Timestamp value) {
      if (createdAtBuilder_ == null) {
        if (((bitField0_ & 0x00000020) != 0) &&
          createdAt_ != null &&
          createdAt_ != com.google.protobuf.Timestamp.getDefaultInstance()) {
          getCreatedAtBuilder().mergeFrom(value);
        } else {
          createdAt_ = value;
        }
      } else {
        createdAtBuilder_.mergeFrom(value);
      }
      if (createdAt_ != null) {
        bitField0_ |= 0x00000020;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp created_at = 6;</code>
     */
    public Builder clearCreatedAt() {
      bitField0_ = (bitField0_ & ~0x00000020);
      createdAt_ = null;
      if (createdAtBuilder_ != null) {
        createdAtBuilder_.dispose();
        createdAtBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp created_at = 6;</code>
     */
    public com.google.protobuf.Timestamp.Builder getCreatedAtBuilder() {
      bitField0_ |= 0x00000020;
      onChanged();
      return getCreatedAtFieldBuilder().getBuilder();
    }
    /**
     * <code>.google.protobuf.Timestamp created_at = 6;</code>
     */
    public com.google.protobuf.TimestampOrBuilder getCreatedAtOrBuilder() {
      if (createdAtBuilder_ != null) {
        return createdAtBuilder_.getMessageOrBuilder();
      } else {
        return createdAt_ == null ?
            com.google.protobuf.Timestamp.getDefaultInstance() : createdAt_;
      }
    }
    /**
     * <code>.google.protobuf.Timestamp created_at = 6;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> 
        getCreatedAtFieldBuilder() {
      if (createdAtBuilder_ == null) {
        createdAtBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>(
                getCreatedAt(),
                getParentForChildren(),
                isClean());
        createdAt_ = null;
      }
      return createdAtBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.example.kafka.Product)
  }

  // @@protoc_insertion_point(class_scope:com.example.kafka.Product)
  private static final ru.prytkovv.demo.proto.Product DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new ru.prytkovv.demo.proto.Product();
  }

  public static ru.prytkovv.demo.proto.Product getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Product>
      PARSER = new com.google.protobuf.AbstractParser<Product>() {
    @java.lang.Override
    public Product parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<Product> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Product> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public ru.prytkovv.demo.proto.Product getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

