// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: product.proto

package ru.prytkovv.demo.proto;

public interface ProductOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.example.kafka.Product)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.com.example.kafka.Image image = 1;</code>
   * @return Whether the image field is set.
   */
  boolean hasImage();
  /**
   * <code>.com.example.kafka.Image image = 1;</code>
   * @return The image.
   */
  ru.prytkovv.demo.proto.Image getImage();
  /**
   * <code>.com.example.kafka.Image image = 1;</code>
   */
  ru.prytkovv.demo.proto.ImageOrBuilder getImageOrBuilder();

  /**
   * <code>string barcode = 2;</code>
   * @return The barcode.
   */
  java.lang.String getBarcode();
  /**
   * <code>string barcode = 2;</code>
   * @return The bytes for barcode.
   */
  com.google.protobuf.ByteString
      getBarcodeBytes();

  /**
   * <code>int32 category_id = 3;</code>
   * @return The categoryId.
   */
  int getCategoryId();

  /**
   * <code>int32 manufacturer_id = 4;</code>
   * @return The manufacturerId.
   */
  int getManufacturerId();

  /**
   * <code>.google.protobuf.Timestamp manufactured_at = 5;</code>
   * @return Whether the manufacturedAt field is set.
   */
  boolean hasManufacturedAt();
  /**
   * <code>.google.protobuf.Timestamp manufactured_at = 5;</code>
   * @return The manufacturedAt.
   */
  com.google.protobuf.Timestamp getManufacturedAt();
  /**
   * <code>.google.protobuf.Timestamp manufactured_at = 5;</code>
   */
  com.google.protobuf.TimestampOrBuilder getManufacturedAtOrBuilder();

  /**
   * <code>.google.protobuf.Timestamp created_at = 6;</code>
   * @return Whether the createdAt field is set.
   */
  boolean hasCreatedAt();
  /**
   * <code>.google.protobuf.Timestamp created_at = 6;</code>
   * @return The createdAt.
   */
  com.google.protobuf.Timestamp getCreatedAt();
  /**
   * <code>.google.protobuf.Timestamp created_at = 6;</code>
   */
  com.google.protobuf.TimestampOrBuilder getCreatedAtOrBuilder();
}
